  
  export const labels = ["DRAINED", "NEUTRAL", "PEAK"];
  
  export const emotionalStates = [
    "joy",
    "love",
    "pride",
    "relief",
    "amusement",
    "awe",
    "hope",
    "gratitude",
    "excitement",
    "calm",
    // "content",
    // "indifferent",
    // "reflective",
    // "sadness",
    // "anger",
    // "fear",
    // "anxiety",
    // "guilt",
    // "shame",
    // "loneliness",
    // "jealousy",
    // "frustration",
  ];

  export const energyStates = [
    "energized",
    "restless",
    "hyper",
    "motivated",
    "stressed",
    "focused",
    // "engaged",
    // "steady",
    // "adaptable",
    // "tired",
    // "sluggish",
    // "calm",
    // "relaxed",
    // "drained",
  ];

  export const mentalStates = [
    "focused",
    "concentrated",
    "distracted",
    "scattered",
    "creative",
    "inspired",
    "overwhelmed",
    "overloaded",
    "clear",
    "mindful",
    "confused",
    "uncertain",
    "flow",
  ];

  export const socialRelationalStates = [
    "connected",
    "supported",
    "appreciated",
    "valued",
    "lonely",
    "isolated",
    "misunderstood",
    "excluded",
    "intimate",
    "close",
    "conflict",
    "tension",
    "empathetic",
    "compassionate",
    "trusting",
    "safe",
  ];

  export const achievementPurposeStates = [
    "motivated",
    "ambitious",
    "purposeful",
    "aligned",
    "accomplished",
    "proud",
    "stagnant",
    "stuck",
    "lost",
    "directionless",
    "hopeful",
    "striving",
    "curious",
    "exploring",
    "resilient",
    "determined",
  ];